### ISSUE TITLE
attach_to_command_entry error

### ISSUE THREAD

**Issue by egency** [jugglerchris/textadept-vi#17]
Hi, whenever I try to type colon ':' in command mode I get the following error:
vi_ce_entry.lua:352: attempt to call nil value (method 'attach_to_command_entry')
None of the other command mode commands work, for example I can't enter visual mode either. The basic hjkl movement keys work however. The version of textadept I'm using is 8.1, not certain what the version of textredux is, however I downloaded it today, so it's pretty much the latest.

I'm really hoping you could fix this (I would, but I can't make head nor tails of what's going on, I figure it's an uninitialized function, but I don't know what it's suppose to do in the first place), if vi-mode for textadept works I'm switching over from vim.

**Comment by jugglerchris** [comment]
Hi,

Currently textadept-vi needs a slightly modified version of textredux from my git clone: https://github.com/jugglerchris/textredux.git

This adds support for using textredux with textadept's command entry buffer (used for `:` commands).

Hope this works for you - and assuming it does, do let me know if you find any missing vi/vim features you miss.

I'm using textadept 8.0 - thanks for prompting me to update to 8.1.  :-)

Chris

**Comment by egency** [comment]
Thank you, that does seem to clear it up. :D I'm not sure how I missed that, I did afterall read that TA-vi uses a modified version of textredux... >_>

The only commands that I miss is :x and the v series, apart from movement those are actually my most used commands. :)

Is there anywhere that explains a bit how it all works? While looking through the code (as someone who has never touched Lua until then mind...) I couldn't figure out where commands where specified, or how they where bound to actions. I'm actually hoping to write an LPEG grammar for orgmode files since TA + vi/vim commands + orgmode seems like a pretty awesome combination to me. :)

**Comment by jugglerchris** [comment]
Hi,

Glad that's working now!

`:x` is easy to add. By the v series, I guess you mean visual mode?  That's more work, but I agree it's a bit of an omission!

There's not much documentation, but roughly:
 * normal (command mode) key bindings are in vi_mode.lua, with movements in vi_motion.lua.
 * ex mode commands (:foo) are in vi_mode_ex.lua.

Generally you can find them in tables full of the functions which do the work. Feel free to ask!

Chris

**Comment by egency** [comment]
Hey,
Yeah, I mean visual mode. :)

The code is actually fairly self explanitory, beautifully written. :) Managed to add the :x command without too much trouble (copied wq and called it x). Also tried to add single character insert, however that went less well. :P

I think I'm going to have to learn Lua first. Which seems like it'll be a breeze, very neat language.

**Comment by jugglerchris** [comment]
Hi,
I added :x last week (sorry about clobbering  your version!), and I've just merged a first attempt at visual mode.  The README says which visual mode commands I've implemented.

I guess this ticket can be closed now - feel free to open another for any other issues or missing features (eg stuff I haven't done yet or is broken in visual mode!)

Chris
