### ISSUE TITLE
Please merge your textredux with latest upstream

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#18]
The current upstream repo has some fixes needed for current textadept.hg.

Thanks!

P.S. I'm reporting this here because your textredux repo seems to have issues disabled.

**Comment by jugglerchris** [comment]
Thanks for pointing it out!  I'll look into it.

**Comment by jugglerchris** [comment]
I've merged the changes.  Things still seem to work for me with Textadept 8.5; let me know if anything's still wrong.

**Comment by mfxmfx** [comment]
Looks good, many thanks!
