### ISSUE TITLE
"cw" does not work with the last word on a line

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#19]
When using "cw" on the last word of a line, the final character is not included in the change.

**Comment by jugglerchris** [comment]
I've reproduced this on the last word of the last line, when it doesn't have a newline.  That certainly is annoying - thanks for reporting!

**Comment by mfxmfx** [comment]
Thanks for your quick fix!

There still is a similar problem for "c2w", though.

**Comment by jugglerchris** [comment]
Hmm, so there is.  I'll have another go!

**Comment by mfxmfx** [comment]
Here is another "cw" issue, probably unrelated: 

  "cw" does include the '.' or ',' when using on "a.b" or "a,b" .

Thanks,
Markus

**Comment by jugglerchris** [comment]
I haven't yet got a fix, but I think I understand the problems now.  Basically "cw" is a special case, and my attempts to bodge the "w" by backtracking over the whitespace falls over at edge cases (eg the end of the file).  Treating it as "ce" is close, but that has different edge cases.  I think I'll just need to manually implement the special "w" motion for the [c]hange command.

**Comment by mfxmfx** [comment]
The following patch is a quick workaround that seems to work in most cases:

-        if pos2 > pos1 and buffer:text_range(pos2, pos2+1):match("%s") then
+        if pos2 > pos1 and not buffer:text_range(pos2, pos2+1):match("[_%w]") then
             -- And back one to step on to the last character of the word.
             pos2 = pos2 - 1
         end

**Comment by jugglerchris** [comment]
I've ditched the "re-use w but try to backtrack" approach and implemented a dedicated one based on documented vim behaviour.  It passes my tests (including extras from this issue) at least!

**Comment by jugglerchris** [comment]
And sorry for taking so long over it - other things have been busy!

**Comment by jugglerchris** [comment]
Optimistically closing the issue.  :-)

**Comment by mfxmfx** [comment]
Great, thanks!
