### ISSUE TITLE
"cw" clears the X11 primary selection

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#21]
I want to paste the X11 primary selection with the middle mouse button.

It seems that using "buffer:set_selection()" instead of "buffer:set_sel()" in 
vi_opts.cut() helps a little bit, but I have no idea about the other implications
of that change.

**Comment by jugglerchris** [comment]
Hi,
Sorry, I'm slightly confused (I almost exclusively use the console version) - do you mean that you want to cut using vi commands and get that added to the X11 primary selection so that you can middle-click paste into another application?
Thanks,
Chris

**Comment by mfxmfx** [comment]
Hi,

no, I want to *paste* the X11 selection - i.e. I mark something in the terminal with the mouse,
switch to textadept-gtk, type "cw" and then the selection is gone (i.e. unselected).

After some quick testing it seems that buffer:set_sel() does unselect the X11 selection, while
buffer:set_selection() does not.

Thanks,
Markus

**Comment by jugglerchris** [comment]
Ah, ok.  Thanks for explaining!  I'll try to understand the difference between set_sel() and set_selection() in an X11 context and see if it makes sense changing.

**Comment by jugglerchris** [comment]
My tests still pass with that change, so I've committed it.  Thanks!
