### ISSUE TITLE
Whitespace cleanup

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#23]
There are a number of files with trailing whitespace, and 4 .lua files with hard tabs - it would be great if this could get cleaned up.

Thanks!

**Comment by jugglerchris** [comment]
I agree.  :-)  I was sort of procrastinating until I found a good Lua formatter, so any suggestions (or indeed pull requests) welcome.

**Comment by mfxmfx** [comment]
Chris, I've created a new pull request - please have a look.

~Markus

**Comment by jugglerchris** [comment]
Awesome, thanks!
Did you use a particular Lua formatter?

**Comment by mfxmfx** [comment]
No, I'm using just a simple Perl script.
