### ISSUE TITLE
Disabling vi-mode in textredux replacements ?

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#27]
Is there an easy way to automatically disable vi-mode in textredux's versions of open_file or buffer_list ?

Please try using this minimal init.lua and press Ctrl+O or Ctrl+B to see what I mean.

Thanks,
Markus

```
local textredux = require('textredux')

package.path = _USERHOME .. "/modules/textadept-vi"  .. "/?.lua;" .. package.path
_G.vi_mode = require('vi_mode')

textredux.hijack()
```

**Comment by jugglerchris** [comment]
Just to be clear, what symptoms do you see?
For me, it seems to work fine with basic use, but if I do a search, it loses the textredux magic (so `enter` doesn't select a file).  I'm not entirely sure why it's happening, or how textredux does its key handling.
There is `vi_mode.restore_keymap` if there's a reasonable way to call `install_keymap` again at the right time.

I would like to get this to work; I don't use `hijack` but I use lists for grep/compiler output and do see the "losing textredux magic" issue sometimes.  Just not *quite* often enough for me to have dug in enough...

**Comment by mfxmfx** [comment]
I don't think this issue can be easily solved, so closing.

**Comment by jugglerchris** [comment]
FWIW I'm open to less easy solutions!

**Comment by mfxmfx** [comment]
Unfortunately I won't work at this - I've switched to the [Howl editor](http://howl.io/) created by the original Textredux author Nils Nordman.

This is still beta and has its own set of vi limitations but overall looks much better thanks to Moonscript and a nice code design.

**Comment by jugglerchris** [comment]
Fair enough!  Thanks again for the improvements you've submitted.  :-)
