### ISSUE TITLE
Request manipulation of text in selected multiple lines

### ISSUE THREAD

**Issue by Nanoc-ice** [jugglerchris/textadept-vi#34]
This request is for the ability to manipulate the same changes when multiple lines are selected. For example I will comment out a function, I will set a mark (ie; ‘a) go to the end of the block and then do :..’as/^/—/. Or use the selection in V (line mode or Ctrl-V) and then shift-i (but this is a very specific use case). 

If there is a preference it would be to identify a range when using the colon.  That would probably cover more use cases.

**Comment by jugglerchris** [comment]
Hi,
Sorry for the delay in replying!  The colon case was nearly there - it just didn't support marks (`:.,+4s/foo/bar/` was already supported).

I've just pushed a change to support marks as addresses to ex commands - let me know if it doesn't work for you!
