### ISSUE TITLE
Question - is it possible to use vi keys in the switch buffer window

### ISSUE THREAD

**Issue by Nanoc-ice** [jugglerchris/textadept-vi#35]
When you bring up the switch buffers window (Ctrl-b), is it possible to move up an down the open buffers with ‘j’ and ‘k’ and return to select?    Yes, the arrow keys work, just wondering if the vi key mappings can be used in other windows panes that pop up.

**Comment by jugglerchris** [comment]
I have to admit I've never used the switch buffers popup.  Which platform are you on?  It doesn't seem to pop up in the terminal Linux version for me, but I may have odd configuration too!

**Comment by Nanoc-ice** [comment]
I am using it under manjaro (arch) linux and using the GUI.  I will want to use the terminal version after I get it all configured appropriately.
As a side note, I am running this linux in a VM using UTM on an iPad Pro.  ATM it is limited to a 1g of memory so I am switching over to using everything light weight.

**Comment by jugglerchris** [comment]
Hi - sorry for the delay in getting back to you.
I believe that the keys for popups are not configurable, mainly as they're not going through the Scintilla editor component unlike most other keys.  :-(

However [textredux](https://github.com/rgieseke/textredux) shows that it's possible to replace the popups with UIs implemented in the editor itself - and I think it includes a buffer switcher you could use.
